project_id = "dbfkdfyworvptxwlvlyn"

[functions.sitemap]
verify_jwt = false

[functions.robots]
verify_jwt = false

[functions.og-meta]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.prerender]
verify_jwt = false
